// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OrderApiApp2.Models
{
    [Table("orders")]
    public partial class Orders
    {
        public Orders()
        {
            Factura = new HashSet<Factura>();
        }

        [Key]
        [Column("id_order")]
        public int IdOrder { get; set; }
        [Column("id_client")]
        public int? IdClient { get; set; }
        [Column("description")]
        [StringLength(200)]
        public string Description { get; set; }

        [ForeignKey("IdClient")]
        [InverseProperty("Orders")]
        public virtual Client IdClientNavigation { get; set; }
        [InverseProperty("IdOrderNavigation")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}